repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-json
      - id: end-of-file-fixer
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
      - id: black
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        files: ^.*\.(py|md|rst|toml)$
  - repo: local
    hooks:
      - id: flakeheaven
        name: flakeheaven
        description: "`Flakeheaven` it's a Flake8 wrapper to make it cool."
        entry: flakeheaven
        args: [ lint ]
        language: python
        types: [ python ]
        require_serial: true
        additional_dependencies: [
          'flake8~=4.0.1',
          'flakeheaven~=1.0.1',
          'flake8-builtins~=2.1.0',
          'flake8-bugbear~=23.3.12',
          'flake8-annotations~=2.9.1',
          'flake8-docstrings~=1.6.0',
          'flake8-bandit~=3.0.0',
        ]
